"""users gain email_verified and a nullable password

Revision ID: 3cde085fb741
Revises: 4c52d03dbf87
Create Date: 2026-08-07 12:44:10.002738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cde085fb741'
down_revision: Union[str, Sequence[str], None] = '4c52d03dbf87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows backfill to false, via the server_default, and that is the decision
    # rather than a side effect: nobody ever proved those addresses. Defaulting them to
    # true would be convenient and would be a lie, and it is the lie that matters — the
    # column exists so that linking a provider identity to a local account on a matching
    # address can require both sides to be verified (#38, #36, #39). A backfill of true
    # would hand every pre-existing account away to whoever registers that address with a
    # provider first.
    #
    # Nothing gates on the column yet, so false locks nobody out today. Whether an
    # unverified user may still sign in is #38's decision, and it is now free to make it.
    #
    # The server_default stays afterwards rather than being dropped. A row inserted by
    # something that is not the ORM — a fixture, a later migration, psql — should come out
    # unverified rather than rejected by the NOT NULL.
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # Accounts reached through a provider have never had a password (#36, #39).
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###
    #
    # Deliberately NOT clearing refresh_tokens. The suggestion on #37 was to make everyone
    # sign in again, and that is right for a rework that moves rows between tables — but
    # this migration only adds a column and relaxes a constraint. `users.id` does not
    # change, so every existing session still points at exactly the person it did before.
    # Logging the whole userbase out would buy nothing.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This fails, by design, if any passwordless account exists: the NOT NULL cannot be
    # restored over a NULL, and there is no honest value to invent for one. An account
    # that only ever signed in through a provider has no password to put back, and
    # inventing an unguessable hash would leave a row that looks like a password account
    # and can never be signed into. Delete those accounts first if this really has to run.
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
