"""acts sequences and scene parentage

Revision ID: 6f268e8ba0a7
Revises: e41ebabe7a00
Create Date: 2026-08-13 14:19:57.358041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f268e8ba0a7'
down_revision: Union[str, Sequence[str], None] = 'e41ebabe7a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acts_campaign_id'), 'acts', ['campaign_id'], unique=False)
    op.create_table('sequences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('act_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequences_act_id'), 'sequences', ['act_id'], unique=False)
    op.create_index(op.f('ix_sequences_campaign_id'), 'sequences', ['campaign_id'], unique=False)
    op.add_column('scenes', sa.Column('act_id', sa.Uuid(), nullable=True))
    op.add_column('scenes', sa.Column('sequence_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_scenes_act_id'), 'scenes', ['act_id'], unique=False)
    op.create_index(op.f('ix_scenes_sequence_id'), 'scenes', ['sequence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenes_sequence_id'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_act_id'), table_name='scenes')
    op.drop_column('scenes', 'sequence_id')
    op.drop_column('scenes', 'act_id')
    op.drop_index(op.f('ix_sequences_campaign_id'), table_name='sequences')
    op.drop_index(op.f('ix_sequences_act_id'), table_name='sequences')
    op.drop_table('sequences')
    op.drop_index(op.f('ix_acts_campaign_id'), table_name='acts')
    op.drop_table('acts')
    # ### end Alembic commands ###
