"""password resets

Revision ID: 86ebc562d0b0
Revises: 0acefdb44e2d
Create Date: 2026-08-07 16:38:16.474204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ebc562d0b0'
down_revision: Union[str, Sequence[str], None] = '0acefdb44e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Its own table rather than a purpose column on email_verifications: this lives an hour
    # rather than a day, belongs to no session because the caller is signed out by
    # definition, and spending it takes the account over rather than confirming a fact
    # about it. Two rows with the same shape and nothing else in common.
    #
    # No foreign key on user_id, matching every other table here.
    op.create_table('password_resets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_token_hash'), 'password_resets', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_token_hash'), table_name='password_resets')
    op.drop_table('password_resets')
    # ### end Alembic commands ###
