"""campaign_and_character_links

Revision ID: 92d10e21c9ed
Revises: 5b17b3c3c19a
Create Date: 2026-07-31 14:36:02.478085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d10e21c9ed'
down_revision: Union[str, Sequence[str], None] = '5b17b3c3c19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_owner_id'), 'campaigns', ['owner_id'], unique=False)
    # Characters predate ownership and there is no owner to give them: an ownerless
    # character is reachable by nobody under the new rule, so it is cleared rather
    # than kept as a row no endpoint can return. Development data only — this schema
    # has never run anywhere else.
    op.execute('DELETE FROM characters')
    op.add_column('characters', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.add_column('characters', sa.Column('campaign_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_characters_campaign_id'), 'characters', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_characters_owner_id'), 'characters', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_owner_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_campaign_id'), table_name='characters')
    op.drop_column('characters', 'campaign_id')
    op.drop_column('characters', 'owner_id')
    op.drop_index(op.f('ix_campaigns_owner_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
