"""character_belongs_to_campaign

Revision ID: ca8c7094b0a1
Revises: 92d10e21c9ed
Create Date: 2026-07-31 15:34:17.529116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8c7094b0a1'
down_revision: Union[str, Sequence[str], None] = '92d10e21c9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('description', sa.Text(), nullable=True))
    # A character now belongs to exactly one campaign, so one at no table cannot be
    # kept: there is no campaign to reach it through, and no route that would return
    # it. Nothing is lost today — the table is empty.
    op.execute('DELETE FROM characters WHERE campaign_id IS NULL')
    op.alter_column('characters', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('characters', 'level')
    op.drop_column('characters', 'character_class')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('character_class', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('characters', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('characters', 'description')
    # ### end Alembic commands ###
