"""user identities

Revision ID: f97697a0da30
Revises: 3cde085fb741
Create Date: 2026-08-07 12:49:25.815398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97697a0da30'
down_revision: Union[str, Sequence[str], None] = '3cde085fb741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The unique constraint is the load-bearing part: one provider account reaches at most
    # one user. Without it two rows could claim the same subject for different accounts and
    # which one a sign-in reached would depend on row order.
    #
    # Keyed on (provider, subject), never on email. A provider's `sub` is stable for the
    # life of that account; an email address is reassignable — routinely so at company
    # domains — and joining on one hands the account to whoever receives the address next.
    #
    # No foreign key on user_id, matching every other table here.
    op.create_table('user_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_user_identities_provider_subject')
    )
    op.create_index(op.f('ix_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_identities_user_id'), table_name='user_identities')
    op.drop_table('user_identities')
    # ### end Alembic commands ###
